version: '3'

services:
## GO ##############################################
  go:
    container_name: golang
    build:
      context: ./Dockerfiles/golang
    volumes:
     - ./../:/app

### COMPOSER ##############################################
  composer:
    build:
      context: ./Dockerfiles/composer
    volumes:
     - ./../:/app
    entrypoint:
     - tail
     - -f
     - /dev/null

### NGINX ##############################################
  nginx:
    build:
      context: ./Dockerfiles/nginx
    volumes:
     - ./DockerFiles/nginx:/etc/nginx/custom
     - ./../:/usr/share/nginx/
    ports:
     - "80:80"
    depends_on:
     - phpfpm
     - mysql
    networks:
     - backend

### MYSQL ##############################################
  mysql:
    image: 'mysql:8'
    command: --default-authentication-plugin=mysql_native_password
    ports:
     - '3399:3306'
    networks:
     - backend
    environment:
     - MYSQL_ROOT_PASSWORD=root

### PHP-FPM ##############################################
  phpfpm:
    working_dir: '/usr/share/nginx/'
    volumes:
     - ./../:/usr/share/nginx/
    build:
      context: ./Dockerfiles/laradock-php-fpm
      args:
        - LARADOCK_PHP_VERSION=7.2
        - INSTALL_MYSQL_CLIENT=true
        - INSTALL_MYSQLI=true
    networks:
     - backend

### ADMINER ##############################################
  adminer:
    volumes:
     - ./../:/app
    image: adminer
    ports:
     - '8080:8080'
    networks:
     - backend

### NODE ##############################################

  node:
    container_name: "node"
    build:
      args:
        version: '8.15'
      context: ./Dockerfiles/node
    working_dir: /home/node/app
    volumes:
     - ./../:/home/node/app

networks:
    backend:
        driver: bridge
    
   
