ARG version
FROM node:$version

#FROM node:8.11.2
# replace this with your application's default port
#RUN yarn global add @vue/cli
#RUN yarn global add @vue/cli-init 
#EXPOSE 8080


RUN npm install --global gulp
